repos:
- repo: local
  hooks:
    - id: scala-cli-fmt
      name: scala-cli fmt
      language: system
      entry: scala-cli fmt .
      files: '\.(scala|sc)$'
    - id: ci_test
      name: scala-cli run ci_test.sc
      language: system
      entry: scala-cli run ci_test.sc
      files: '\.(scala|sc)$'
      stages: [push]
