FROM trailofbits/polytracker:latest

ARG USER
ARG UID
ARG GID
ENV USER=$USER
ENV UID=$UID
ENV GID=$GID
ENV HOME /home/$USER

WORKDIR /build

### Allow sudo
RUN mkdir -p /etc/sudoers.d && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${USER}

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update

### C
RUN apt install -y build-essential pkg-config binutils gdb curl lsb-release wget software-properties-common ninja-build

### Python
RUN apt install -y python3 python3-pip python3-dev libpython3-dev
RUN python3 -m pip install virtualenv ptpython ipdb

### Utilities
RUN apt install -y sudo curl zip unzip vim git moreutils silversearcher-ag strace ltrace graphviz cairosvg locales
RUN apt install -y linux-tools-generic linux-tools-`uname -r`
RUN locale-gen ja_JP.UTF-8

### Install graph-tool
RUN add-apt-repository "deb [ arch=amd64 ] https://downloads.skewed.de/apt jammy main"
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7A80C8ED4FCCBE09
RUN apt update && apt install -y python3-graph-tool libcairomm-1.0-dev
RUN pip3 install "numpy<2" scipy pycairo==1.26.1 matplotlib

### Create user
### NOTE: ホームディレクトリはマウントポイントとして使う
RUN useradd --create-home --home-dir /home/${USER} --uid ${UID} ${USER}
RUN usermod -aG sudo ${USER}

ENV WLLVM_BC_STORE=/project_bitcode
ENV WLLVM_ARTIFACT_STORE=/project_artifacts
RUN chown -R ${USER}:${USER} ${WLLVM_BC_STORE} ${WLLVM_ARTIFACT_STORE}

### Change default user
USER ${USER}

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8