name: Trunk Lint

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request: {}
  merge_group: {}

permissions: read-all

jobs:
  lint:
    uses: trailofbits/.github/.github/workflows/lint.yml@v0.1.3
    permissions:
      contents: read
      pull-requests: read
      checks: write
